// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUNixj33mfpf0AAlJNv7UzfhsTWzVSFfk',
    appId: '1:385329168156:web:5471adeb84805026a404d9',
    messagingSenderId: '385329168156',
    projectId: 'videojueves-fc73c',
    authDomain: 'videojueves-fc73c.firebaseapp.com',
    storageBucket: 'videojueves-fc73c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe04vZRtFf0-O1ZusZN44snz97GRq2X1Y',
    appId: '1:385329168156:android:9137a078c1c8af49a404d9',
    messagingSenderId: '385329168156',
    projectId: 'videojueves-fc73c',
    storageBucket: 'videojueves-fc73c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACDS7epz4dOAwSGqe59hrG6xF7LbK1-qQ',
    appId: '1:385329168156:ios:25b43a3a5f3c1973a404d9',
    messagingSenderId: '385329168156',
    projectId: 'videojueves-fc73c',
    storageBucket: 'videojueves-fc73c.firebasestorage.app',
    iosBundleId: 'com.example.videoJueves',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACDS7epz4dOAwSGqe59hrG6xF7LbK1-qQ',
    appId: '1:385329168156:ios:25b43a3a5f3c1973a404d9',
    messagingSenderId: '385329168156',
    projectId: 'videojueves-fc73c',
    storageBucket: 'videojueves-fc73c.firebasestorage.app',
    iosBundleId: 'com.example.videoJueves',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUNixj33mfpf0AAlJNv7UzfhsTWzVSFfk',
    appId: '1:385329168156:web:ff52463ef7dd0c78a404d9',
    messagingSenderId: '385329168156',
    projectId: 'videojueves-fc73c',
    authDomain: 'videojueves-fc73c.firebaseapp.com',
    storageBucket: 'videojueves-fc73c.firebasestorage.app',
  );
}
